"""
api.py — The ML Server
========================
This is the bridge between your ML model and your backend person's Node server.

HOW IT WORKS:
  1. Node backend sends a bridge image to POST /predict
  2. This server runs the image through the trained CNN model
  3. Gets 4 predictions (crack, structure, severity, timeline)
  4. Fuses them into a risk level (low/medium/high/critical)
  5. Calls Claude API to generate a human-readable report
  6. Returns everything as a single JSON response to Node

WHY FASTAPI?
  FastAPI is a modern Python web framework that:
  - Is extremely fast (built on async I/O)
  - Automatically generates API documentation at /docs
  - Validates request/response shapes with Pydantic
  - Works perfectly with PyTorch

START THE SERVER:
  uvicorn api:app --host 0.0.0.0 --port 8000

  --host 0.0.0.0  means "accept connections from any machine"
                  (not just localhost). Needed for Docker.
  --port 8000     your Node backend calls this port.
"""

import io
import os
import math
import json
import torch
import requests
from PIL import Image
from fastapi import FastAPI, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from typing import List, Dict

from model   import BridgeFailureModel, DAMAGE_CLASSES, STRUCTURE_CLASSES
from dataset import VAL_TRANSFORMS


# ── Create the FastAPI app ────────────────────────────────────────────────────
app = FastAPI(
    title="Bridge Failure Prediction API",
    description="Upload a bridge image → get damage type, severity, timeline, and repair report.",
    version="1.0.0"
)

# CORS middleware allows the Node server (and potentially a browser)
# to call this API from a different origin/port.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],   # In production, change to your backend's URL
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Load model at startup ─────────────────────────────────────────────────────
# We load the model ONCE when the server starts, not on every request.
# Loading a model takes ~2-3 seconds. We can't afford that per API call.
CHECKPOINT = os.environ.get("MODEL_CHECKPOINT", "checkpoints/bridge_model.pt")
DEVICE     = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print(f"Loading model from: {CHECKPOINT}")
print(f"Running on: {DEVICE}")

model = BridgeFailureModel()
model.load_state_dict(
    torch.load(CHECKPOINT, map_location=DEVICE)
    # map_location=DEVICE handles the case where you trained on GPU
    # but are running inference on CPU (or vice versa)
)
model.to(DEVICE).eval()
# .eval() puts the model in inference mode:
# - Disables Dropout (use all neurons — most stable output)
# - Disables BatchNorm training behavior
print("Model loaded and ready.")


# ── Response schema ───────────────────────────────────────────────────────────
# Pydantic models define the exact shape of the JSON we return.
# FastAPI uses these to validate the response and generate /docs.

class ReportSection(BaseModel):
    """The 4-section maintenance report generated by Claude."""
    what:       str        # What damage was found
    why:        str        # Why it likely happened
    when:       str        # Timeline and urgency
    next_steps: List[str]  # Actionable recommendations

class PredictionResponse(BaseModel):
    """The complete JSON response sent back to the Node backend."""
    damage_detected:     bool           # True if crack was found
    damage_confidence:   float          # 0.0-1.0, how sure the model is
    structure_type:      str            # deck / pavement / wall
    severity_score:      float          # 0-100, structural health
    days_to_failure:     int            # estimated days to critical state
    risk_level:          str            # low / medium / high / critical
    class_probabilities: Dict[str, float]  # probability for each damage class
    report:              ReportSection  # full Claude-generated report


# ── Risk fusion logic ─────────────────────────────────────────────────────────

def fuse_risk(cracked: bool, severity: float, days: float) -> str:
    """
    Combines the 3 regression/classification outputs into a single risk level.

    Logic:
    - If no crack detected and structure is healthy → low
    - If imminent failure (<30 days) or severely damaged (<20 score) → critical
    - If failure within 90 days or moderate damage → high
    - If cracked but not immediately dangerous → medium
    - Otherwise → low

    This is a rule-based fusion. Once you have enough labelled predictions
    with known outcomes, you could replace this with a trained meta-classifier.
    """
    if not cracked and severity > 80:
        return "low"
    if days < 30 or severity < 20:
        return "critical"
    if days < 90 or severity < 40:
        return "high"
    if cracked or severity < 60:
        return "medium"
    return "low"


# ── LLM report generation ─────────────────────────────────────────────────────

def generate_report(cracked: bool, structure: str,
                    severity: float, days: int, risk: str) -> dict:
    """
    Calls Claude to generate a structured maintenance report.

    WHY JSON FROM THE LLM?
    We ask Claude to respond ONLY in JSON so we can parse it into
    structured fields (what, why, when, next_steps). This lets the
    frontend display each section separately rather than one big text blob.

    FALLBACK:
    If the API call fails for any reason (network, missing key, etc.),
    we return a basic fallback report so the API never crashes.
    """
    api_key   = os.environ.get("ANTHROPIC_API_KEY", "")
    condition = "cracking detected" if cracked else "no visible cracks"

    prompt = f"""You are a structural engineering AI assistant.
A bridge inspection image has been analysed with the following results:

- Structure type: {structure}
- Condition: {condition}
- Structural health score: {severity:.1f} out of 100 (lower = more damaged)
- Estimated days to critical failure: {days}
- Overall risk level: {risk.upper()}

Respond ONLY with a valid JSON object — no markdown, no extra text, just JSON:
{{
  "what": "One clear paragraph describing the damage found and its visible characteristics",
  "why": "One paragraph explaining 2-3 likely root causes (material fatigue, weathering, load cycles, poor drainage, etc.)",
  "when": "One paragraph interpreting the {days}-day estimate: is this urgent? What does it mean practically?",
  "next_steps": [
    "Specific action 1",
    "Specific action 2",
    "Specific action 3",
    "Specific action 4"
  ]
}}"""

    if not api_key:
        print("WARNING: ANTHROPIC_API_KEY not set. Returning fallback report.")
        return _fallback_report(cracked, structure, days)

    try:
        resp = requests.post(
            "https://api.anthropic.com/v1/messages",
            headers={
                "x-api-key":           api_key,
                "anthropic-version":   "2023-06-01",
                "content-type":        "application/json",
            },
            json={
                "model":      "claude-sonnet-4-20250514",
                "max_tokens": 700,
                "messages":   [{"role": "user", "content": prompt}],
            },
            timeout=30,
        )
        resp.raise_for_status()
        raw_text = resp.json()["content"][0]["text"]
        return json.loads(raw_text)

    except Exception as e:
        print(f"Claude API error: {e}. Returning fallback report.")
        return _fallback_report(cracked, structure, days)


def _fallback_report(cracked: bool, structure: str, days: int) -> dict:
    """Returns a basic report if the Claude API call fails."""
    condition = "Cracking" if cracked else "No cracks"
    return {
        "what":       f"{condition} detected on {structure} structure.",
        "why":        "Root cause analysis requires manual review by a structural engineer.",
        "when":       f"Based on model estimates, intervention may be needed within {days} days.",
        "next_steps": [
            "Schedule a professional on-site inspection",
            "Document the damage with dated photographs",
            "Review the maintenance and load history",
            "Consult a licensed structural engineer",
        ],
    }


# ── API Routes ────────────────────────────────────────────────────────────────

@app.get("/")
def root():
    """Basic health check — confirms the server is running."""
    return {
        "status":  "running",
        "message": "Bridge Failure Prediction API",
        "docs":    "Visit /docs for interactive API documentation",
    }

@app.get("/health")
def health():
    """
    Health check endpoint used by Docker's healthcheck and your backend person.
    docker-compose waits for this to return 200 before starting the Node server.
    """
    return {
        "status":     "ok",
        "device":     str(DEVICE),
        "checkpoint": CHECKPOINT,
    }

@app.post("/predict", response_model=PredictionResponse)
async def predict(file: UploadFile = File(...)):
    """
    POST /predict
    =============
    Receives a bridge image and returns a full analysis.

    REQUEST:
      Content-Type: multipart/form-data
      Field name: "file"
      File: JPEG, PNG, or WEBP image

    RESPONSE: PredictionResponse JSON (see schema above)

    HOW YOUR BACKEND PERSON CALLS THIS:
      const form = new FormData();
      form.append('file', imageBuffer, filename);
      const result = await axios.post('http://ml_api:8000/predict', form);
    """
    # Validate that the uploaded file is actually an image
    if file.content_type not in ("image/jpeg", "image/png", "image/webp"):
        raise HTTPException(
            status_code=400,
            detail=f"Unsupported file type: {file.content_type}. Use JPEG, PNG, or WEBP."
        )

    # Read image bytes and convert to PIL Image
    contents = await file.read()
    try:
        pil_image = Image.open(io.BytesIO(contents)).convert("RGB")
    except Exception:
        raise HTTPException(status_code=400, detail="Could not open image file. Is it corrupted?")

    # Preprocess: resize → normalize → add batch dimension
    # unsqueeze(0) adds a batch dimension: (3, 300, 300) → (1, 3, 300, 300)
    # The model expects batches, even if we're only processing 1 image.
    tensor = VAL_TRANSFORMS(pil_image).unsqueeze(0).to(DEVICE)

    # Run the model — no gradient computation needed at inference time
    with torch.no_grad():
        outputs = model(tensor)

    # ── Parse Head 1: Crack detection ────────────────────────────────────────
    # softmax converts raw logits to probabilities that sum to 1.0
    # e.g. [0.2, 3.8] → [0.02, 0.98] (98% cracked)
    damage_probs = torch.softmax(outputs["damage_logits"], dim=1)[0]
    damage_idx   = damage_probs.argmax().item()
    cracked      = (damage_idx == 1)
    confidence   = damage_probs[damage_idx].item()

    # ── Parse Head 2: Structure type ─────────────────────────────────────────
    struct_probs = torch.softmax(outputs["structure_logits"], dim=1)[0]
    struct_idx   = struct_probs.argmax().item()
    structure    = STRUCTURE_CLASSES[struct_idx]

    # ── Parse Head 3: Severity score ─────────────────────────────────────────
    severity = round(outputs["severity"][0, 0].item(), 1)
    severity = max(0.0, min(100.0, severity))   # clamp to [0, 100]

    # ── Parse Head 4: Days to failure ────────────────────────────────────────
    # The model outputs log(days+1). We reverse with expm1 = e^x - 1.
    log_val = outputs["timeline_log"][0, 0].item()
    days    = max(1, round(math.expm1(log_val)))

    # ── Fuse into risk level ──────────────────────────────────────────────────
    risk = fuse_risk(cracked, severity, days)

    # ── Generate Claude report ────────────────────────────────────────────────
    report_dict = generate_report(cracked, structure, severity, days, risk)

    # ── Build and return response ─────────────────────────────────────────────
    return PredictionResponse(
        damage_detected     = cracked,
        damage_confidence   = round(confidence, 4),
        structure_type      = structure,
        severity_score      = severity,
        days_to_failure     = days,
        risk_level          = risk,
        class_probabilities = {
            DAMAGE_CLASSES[i]: round(damage_probs[i].item(), 4)
            for i in range(len(DAMAGE_CLASSES))
        },
        report = ReportSection(**report_dict),
    )
